# Setup:
#   mamba env create -f conda.yaml
#   mamba activate spatialcells
#   pip install --no-deps .

# Use conda-scimap.yaml instead if you need scimap in the same env as well.

name: spatialcells

channels:
  - conda-forge

dependencies:
  - python >=3.10,<3.13
  - pip
  - ipykernel
  - nbconvert
  - nbclient

  # Core runtime
  - shapely >=2.0 
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - leidenalg
  - scanpy
  - anndata

  # Optional: for joint analyses with other packages (as was done in the tutorials)
  - squidpy
  - plotly
